services:

    blaster_task.newsletter_subscriber:
        class: Blaster\TaskBundle\EventListener\NewsletterSignupListener
        arguments: ["@doctrine.orm.default_entity_manager", "@validator", "@logger"]
        tags:
            - { name: kernel.event_listener, event: subscribe_newsletter, method: subscribeNewsletter }

#    blaster_task.blaster_manager:
#        class: Blaster\TaskBundle\Services\BlasterManager
#        arguments: ["@doctrine.orm.default_entity_manager", "@validator"]
